# Generated by Django 4.2.1 on 2023-05-31 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityCampus',
        ),
    ]
